import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import MainLayout from "../components/layouts/MainLayout";
import ContentLayout from "../components/layouts/ContentLayout";
import { Divider, Stack } from "@chakra-ui/react";
import CreateFeedBox from "../components/Home/CreateFeedBox";
import TopBar from "../components/Home/Topbar";
import Feed from "../components/Feed";
import Right from "../components/common/Right";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Social network</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <ContentLayout
          left={
            <Stack>
              <TopBar />
              <CreateFeedBox />
              <Divider py={3} />
              <Stack spacing={0}>
                <>
                  <Feed />
                  <Divider />
                </>
                <>
                  <Feed />
                  <Divider />
                </>
                <>
                  <Feed />
                  <Divider />
                </>
              </Stack>
            </Stack>
          }
          right={<Right />}
        />
      </MainLayout>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );
  return <></>;
};
